# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: leikor.de
  password: leikor.de
  host: localhost
  port: 5432

development:
  <<: *common
  database: leikor_de

test:
  <<: *common
  database: leikor_de_test
