#!/bin/bash

PID_FILE='tmp/pids/spork.pid'
LOG_FILE='log/spork.log'

ANIMATION='⠁⠃⠇⠧⠶⠼⠹⠙⠉⠁'
ANIMATION='⠁⠂⠄⡀⢀⠠⠐⠈'
ANIMATION='⠀⣀⣤⣶⣿⠿⠛⠉⠀⠉⠛⠿⣿⣶⣤⣀'
SLEEP_TIME=0.15

if [[ -e "$PID_FILE" ]]; then
  PID=`cat "$PID_FILE"`
  if ( kill -KILL $PID &> /dev/null ); then
    echo "$(date +'[%F %T]') Killed Spork with PID=$PID" | tee "$LOG_FILE"
  else
    echo "$(date +'[%F %T]') Spork was not running."
    echo "$(date +'[%F %T]') Removing lock file ..."
  fi
  rm -f "$PID_FILE"
else
  echo "$(date +'[%F %T]') Logging output to ´$LOG_FILE´."
  echo -n "$(date +'[%F %T]') Starting Spork ..."
  spork &>> "$LOG_FILE" & PID=$!

  echo $PID > "$PID_FILE"
  PROC_FD="/proc/$PID"
  WAITING=0
  echo -n " ${ANIMATION:WAITING:1}"
  while (( $WAITING + 1 )); do
    REPLY=`tail -n 1 "$LOG_FILE"`
    if [[ "$REPLY" == Spork\ is\ ready* ]]; then
      WAITING=-1
      notify-send -i stock_yes "$REPLY"
      echo -e "\\bdone"
    elif [[ ! -e "$PROC_FD" ]]; then
      WAITING=-1
      echo -e "\\bdied"
      echo "$(date +'[%F %T]') Removing lock file ..."
      rm -f "$PID_FILE"
      notify-send -i stock_stop "Spork died." "Showing logs ..."
      less +G "$LOG_FILE"
    else
      WAITING=$(( (WAITING + 1) % ${#ANIMATION} ))
      echo -ne "\\b${ANIMATION:WAITING:1}"
      sleep $SLEEP_TIME
    fi
  done
fi
